import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { WindowManagerProvider } from "./context/WindowManagerContext";
import { SpotlightProvider } from "./context/SpotlightContext";
import Spotlight from "@/components/Spotlight/Spotlight";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <WindowManagerProvider>
          <SpotlightProvider>
            {children}
            <Spotlight /> 
          </SpotlightProvider>
        </WindowManagerProvider>
      </body>
    </html>
  );
}
